# Default values for test-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

tsunami:
  name: tsunami-scanner
  image:
    repository: fadyabuhatoum/tsunami-security-scanner:latest
    pullPolicy: Always # We have also Always to pull it & latest 
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  volumeMounts:
    mountPath: /usr/tsunami/logs
    name: volumes-tsunami-logs
  volumes:
    name: volumes-tsunami-logs
    hostPath:
      path: /opt/logs
  env:
    name: ip
    value: ""

unauthenticated:
  image: jupyter/base-notebook
  name: unauthenticated-jupyter
  containerName: unauthenticated-container
  pullPolicy: Always
  tag: ""
  command: ["/bin/sh","-c"]
  args: ["start-notebook.sh; --NotebookApp.token='' "]
  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
#   # We usually recommend not to specify default resources and to leave this as a conscious
#   # choice for the user. This also increases chances charts run on environments with little
#   # resources, such as Minikube. If you do want to specify resources, uncomment the following
#   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  jupyter:
    limits: 
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  tsunami:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
